#!/usr/bin/env bash

mkdir ./_locales
rm -rf ./_locales/*


while read line;do
	echo $line
	mkdir -p ./_locales/$line 2>/dev/null

	name=$(trans -brief -from en -to "$line" "Copy Tabs")
	desc=$(trans -brief -from en -to $line "Copy Tabs as hyperlinks or text URLs with or without parameters")
	cpytablnk=$(trans -brief -from en -to $line "This Tab as Link")
	cpytabtxt=$(trans -brief -from en -to $line "This Tab as Text URL")
	cpyalllnk=$(trans -brief -from en -to $line "All Tabs as Links")
	cpyalltxt=$(trans -brief -from en -to $line "All Tabs as Text URLs")
	cpysellnk=$(trans -brief -from en -to $line "Selected Tabs as Links")
	cpyseltxt=$(trans -brief -from en -to $line "Selected Tabs as Text URLs")

	cpytablnknp=$(trans -brief -from en -to $line "This Tab as Link (Strip Parameters)")
	cpytabtxtnp=$(trans -brief -from en -to $line "This Tab as Text URL (Strip Parameters)")
	cpyalllnknp=$(trans -brief -from en -to $line "All Tabs as Links (Strip Parameters)")
	cpyalltxtnp=$(trans -brief -from en -to $line "All Tabs as Text URLs (Strip Parameters)")
	cpysellnknp=$(trans -brief -from en -to $line "Selected Tabs as Links (Strip Parameters)")
	cpyseltxtnp=$(trans -brief -from en -to $line "Selected Tabs as Text URLs (Strip Parameters)")

	selectaction=$(trans -brief -from en -to $line "Select button action")

	JSON=$(cat << EOI

{
  "addonName": {
    "message": "$name",
    "description": ""
  },
  "addonDesc": {
    "message": "$desc",
    "description": ""
  },
  "selectaction": {
    "message": "$selectaction",
    "description": ""
  },
  "cpyalllnk": {
    "message": "$cpyalllnk",
    "description": ""
  },
  "cpyalltxt": {
    "message": "$cpyalltxt",
    "description": ""
  },
  "cpysellnk": {
    "message": "$cpysellnk",
    "description": ""
  },
  "cpyseltxt": {
    "message": "$cpyseltxt",
    "description": ""
  },
  "cpytabtxt": {
    "message": "$cpytabtxt",
    "description": ""
  },
  "cpytablnk": {
    "message": "$cpytablnk",
    "description": ""
  },
  "cpyalllnknp": {
    "message": "$cpyalllnknp",
    "description": ""
  },
  "cpyalltxtnp": {
    "message": "$cpyalltxtnp",
    "description": ""
  },
  "cpysellnknp": {
    "message": "$cpysellnknp",
    "description": ""
  },
  "cpyseltxtnp": {
    "message": "$cpyseltxtnp",
    "description": ""
  },
  "cpytabtxtnp": {
    "message": "$cpytabtxtnp",
    "description": ""
  },
  "cpytablnknp": {
    "message": "$cpytablnknp",
    "description": ""
  }
}
EOI
)

echo $JSON | jq '.' -r > _locales/$line/messages.json

done << EOH
	af
	sq
	am
	ar
	hy
	az
	ba
	eu
	bn
	bs
	bg
	ca
	ny
	co
	hr
	cs
	da
	nl
	en
	eo
	et
	fj
	tl
	fi
	fr
	fy
	gl
	ka
	de
	el
	gu
	ht
	ha
	he
	hi
	hu
	is
	ig
	id
	ga
	it
	ja
	jv
	kn
	kk
	km
	ku
	ky
	lo
	la
	lv
	lt
	lb
	mk
	mg
	ms
	ml
	mt
	mi
	mr
	mn
	my
	ne
	no
	ps
	fa
	pl
	pt
	pa
	ro
	ru
	sm
	gd
	st
	sn
	sd
	si
	sk
	sl
	so
	es
	su
	sw
	sv
	ty
	tg
	ta
	tt
	te
	th
	to
	tr
	udm
	uk
	ur
	uz
	vi
	cy
	xh
	yi
	yo
	zu
EOH

