#!/usr/bin/env bash

mkdir ./_locales
rm -rf ./_locales/*


while read line;do
	echo $line
	mkdir -p ./_locales/$line 2>/dev/null

	name=$(trans -brief -from en -to "$line" "Copy Tabs")
	desc=$(trans -brief -from en -to $line "Copy tab urls as hyperlinks or plain text")

	selectaction=$(trans -brief -from en -to $line "Select Immediate Action")
	cpytablnk=$(trans -brief -from en -to $line "This Tab as Link")
	cpytabtxt=$(trans -brief -from en -to $line "This Tab as Text URL")
	cpyalllnk=$(trans -brief -from en -to $line "All Tabs as Links")
	cpyalltxt=$(trans -brief -from en -to $line "All Tabs as Text URLs")
	cpysellnk=$(trans -brief -from en -to $line "Selected Tabs as Links")
	cpyseltxt=$(trans -brief -from en -to $line "Selected Tabs as Text URLs")

	cpytablnknp="$cpytablnk (✂️)"
	cpytabtxtnp="$cpytabtxt (✂️)"
	cpyalllnknp="$cpyalllnk (✂️)"
	cpyalltxtnp="$cpyalltxt (✂️)"
	cpysellnknp="$cpysellnk (✂️)"
	cpyseltxtnp="$cpyseltxt (✂️)"

    tip1="The active tab is always selected"
    tip2="Use the CTRL key to select additional tabs"
    tip3="Use the SHIFT key to select a range of tabs"
    tip4="All copy actions can be assigned to hotkeys/shortcuts"
    tip5="All copy actions are also available via the tab context menu"
    tip6="LMB and MMB action of the toolbar button can be switched"
    tip7="Use MMB/LMB to immediately invoke a copy action"
    tip8="Change the immediate copy action via the toolbar buttons context menu"
    tip9="Give the developers feedback so they'll know what is good and what needs impovement"

	JSON=$(cat << EOI

{
  "addonName": {
    "message": "$name",
    "description": ""
  },
  "addonDesc": {
    "message": "$desc",
    "description": ""
  },
  "selectaction": {
    "message": "$selectaction",
    "description": ""
  },
  "cpyalllnk": {
    "message": "$cpyalllnk",
    "description": ""
  },
  "cpyalltxt": {
    "message": "$cpyalltxt",
    "description": ""
  },
  "cpysellnk": {
    "message": "$cpysellnk",
    "description": ""
  },
  "cpyseltxt": {
    "message": "$cpyseltxt",
    "description": ""
  },
  "cpytabtxt": {
    "message": "$cpytabtxt",
    "description": ""
  },
  "cpytablnk": {
    "message": "$cpytablnk",
    "description": ""
  },
  "cpyalllnknp": {
    "message": "$cpyalllnknp",
    "description": ""
  },
  "cpyalltxtnp": {
    "message": "$cpyalltxtnp",
    "description": ""
  },
  "cpysellnknp": {
    "message": "$cpysellnknp",
    "description": ""
  },
  "cpyseltxtnp": {
    "message": "$cpyseltxtnp",
    "description": ""
  },
  "cpytabtxtnp": {
    "message": "$cpytabtxtnp",
    "description": ""
  },
  "cpytablnknp": {
    "message": "$cpytablnknp",
    "description": ""
  },
  "tip1": {
    "message": "$tip1",
    "description": ""
  },
  "tip2": {
    "message": "$tip2",
    "description": ""
  },
  "tip3": {
    "message": "$tip3",
    "description": ""
  },
  "tip4": {
    "message": "$tip4",
    "description": ""
  },
  "tip5": {
    "message": "$tip5",
    "description": ""
  },
  "tip6": {
    "message": "$tip6",
    "description": ""
  },
  "tip7": {
    "message": "$tip7",
    "description": ""
  },
  "tip8": {
    "message": "$tip8",
    "description": ""
  },
  "tip9": {
    "message": "$tip9",
    "description": ""
  }
}
EOI
)

echo $JSON | jq '.' -r > _locales/$line/messages.json

done << EOH
	af
	sq
	am
	ar
	hy
	az
	ba
	eu
	bn
	bs
	bg
	ca
	ny
	co
	hr
	cs
	da
	nl
	en
	eo
	et
	fj
	tl
	fi
	fr
	fy
	gl
	ka
	de
	el
	gu
	ht
	ha
	he
	hi
	hu
	is
	ig
	id
	ga
	it
	ja
	jv
	kn
	kk
	km
	ku
	ky
	lo
	la
	lv
	lt
	lb
	mk
	mg
	ms
	ml
	mt
	mi
	mr
	mn
	my
	ne
	no
	ps
	fa
	pl
	pt
	pa
	ro
	ru
	sm
	gd
	st
	sn
	sd
	si
	sk
	sl
	so
	es
	su
	sw
	sv
	ty
	tg
	ta
	tt
	te
	th
	to
	tr
	uk
	ur
	uz
	vi
	cy
	xh
	yi
	yo
	zu
EOH

